### PR TITLE
Fixes issue 50: detecting if user is already logged in

### LINKED ISSUE #50: autoload not working properly
Hello, 
I'm using a simple callback for my FacebookLogin. It basically sets a variable to true if the response is "connected". I have autoLoad on, and my callback is being called as soon as the component is loaded, but the response on autoLoad is always "unknown". Even though when I press the button I'm instantly logged in (prompt doesn't ask for username and password again unless I use FB.logout()) which means that autoLoad should get back a "connected" response.

Am I missing something?
Thanks

### PR DESCRIPTION
**Pull request by SebastienMelki**
I want to resolve #50. This fixed the issue I was having..not sure if it's the proper way to go. Thoughts?

### CODE REVIEW

File: src/facebook.js [hunk 1]
```diff
@@ -75,6 +75,15 @@ class FacebookLogin extends React.Component {
     });
   };
 
+  // When page refreshes sometimes response is unknown and we need to call window.FB.login again 
+  checkLoginAfterRefresh = (response) => {
+    if (response.status === "unknown") {
+      window.FB.login((function(response) {
+        this.checkLoginState(response);
+      }).bind(this), true);
```
Comment (keppelen) [inline src/facebook.js]: @SebastienMelki ES6 sintaxe please?

Comment (revolunet) [inline src/facebook.js]: this works for me, it allows to restore the Login on page refresh 👍 

```js
  checkLoginAfterRefresh = (response) => {
    if (response.status === "unknown") {
      window.FB.login(loginResponse => this.checkLoginState(loginResponse), true)
    }
  };
```
